### ISSUE TITLE
Recursive mixins

### ISSUE THREAD

**Issue by mendrik** [postcss/postcss-mixins#71] opened 2017-05-29 13:12 UTC
Hi I'm fairly new to postcss so the issue might be between keyboard and chair, but I was trying to get a recursive rule generation working like so:

```
@define-mixin dept $i {
    @if ($i > 0) {
        > li {
           @mixin dept resolve($i - 1);
        }
    }
}

ul {
    @mixin dept 5;
}
```

But this results in 
```
Module build failed: RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at simpleSyntax ([...]node_modules\postcss-simple-vars\index.js:34:16)
    at bothSyntaxes ([...]node_modules\postcss-simple-vars\index.js:46:11)
    at [...]node_modules\postcss-simple-vars\index.js:81:16
    at repeat ([...]node_modules\postcss-simple-vars\index.js:56:20)
    at atruleParams ([...]node_modules\postcss-simple-vars\index.js:80:19)
    at [...]node_modules\postcss-simple-vars\index.js:136:21
    at [...]node_modules\postcss\lib\container.es6:110:26
    at Root.each ([...]node_modules\postcss\lib\container.es6:78:22)
    at Root.walk ([...]node_modules\postcss\lib\container.es6:109:21)
    at [...]node_modules\postcss-simple-vars\index.js:117:13
    at insertMixin ([...]node_modules\postcss-mixins\index.js:62:35)
    at [...]node_modules\postcss-mixins\index.js:140:25
    at [...]node_modules\postcss\lib\container.es6:252:28
```

**Comment by ai** [comment] 2017-05-29 17:13
Thanks for report. I look into it, when I will return to good Internet at 9 June.

**Comment by ai** [comment] 2017-06-11 00:18
The problem is in PostCSS limits. In PostCSS plugins are applying one-by one. In your case, first `postcss-mixins` are applying, then `postcss-if` and then `postcss-resolve`. In result, you have infinity loop, because `@if` will be applied only when `postcss-mixins` will be finished (so never).

There are two solution right now:

1. Wait for Plugin Event API https://github.com/postcss/postcss/issues/296 — it will fix this limit. But we didn’t plan to resole it at least in this summer (full refactoring with really small amount of users, who need it).
2. Write “Function Mixin” on JS, so`if` will be inside mixin. Here are a docs https://github.com/postcss/postcss-mixins#function-mixin

**Closed by ai** 2017-06-11 00:18 UTC

**Comment by mendrik** [comment] 2017-06-14 06:46
alrighty, thanks for looking into this!
